import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Comprehensive list of Nigerian universities, polytechnics, and colleges  
const NIGERIAN_SCHOOLS = [
    // Federal Universities
    { name: 'University of Lagos', type: 'Federal University', state: 'Lagos', city: 'Akoka' },
    { name: 'University of Ibadan', type: 'Federal University', state: 'Oyo', city: 'Ibadan' },
    { name: 'University of Nigeria, Nsukka', type: 'Federal University', state: 'Enugu', city: 'Nsukka' },
    { name: 'Obafemi Awolowo University', type: 'Federal University', state: 'Osun', city: 'Ile-Ife' },
    { name: 'Ahmadu Bello University', type: 'Federal University', state: 'Kaduna', city: 'Zaria' },
    { name: 'University of Benin', type: 'Federal University', state: 'Edo', city: 'Benin City' },
    { name: 'University of Ilorin', type: 'Federal University', state: 'Kwara', city: 'Ilorin' },
    { name: 'University of Jos', type: 'Federal University', state: 'Plateau', city: 'Jos' },
    { name: 'University of Calabar', type: 'Federal University', state: 'Cross River', city: 'Calabar' },
    { name: 'University of Port Harcourt', type: 'Federal University', state: 'Rivers', city: 'Port Harcourt' },
    { name: 'University of Maiduguri', type: 'Federal University', state: 'Borno', city: 'Maiduguri' },
    { name: 'Bayero University Kano', type: 'Federal University', state: 'Kano', city: 'Kano' },
    { name: 'University of Abuja', type: 'Federal University', state: 'FCT', city: 'Abuja' },
    { name: 'Nnamdi Azikiwe University', type: 'Federal University', state: 'Anambra', city: 'Awka' },
    { name: 'University of Uyo', type: 'Federal University', state: 'Akwa Ibom', city: 'Uyo' },
    { name: 'Federal University of Technology, Akure', type: 'Federal University', state: 'Ondo', city: 'Akure' },
    { name: 'Federal University of Technology, Minna', type: 'Federal University', state: 'Niger', city: 'Minna' },
    { name: 'Federal University of Technology, Owerri', type: 'Federal University', state: 'Imo', city: 'Owerri' },
    { name: 'Modibbo Adama University', type: 'Federal University', state: 'Adamawa', city: 'Yola' },
    { name: 'Usmanu Danfodiyo University', type: 'Federal University', state: 'Sokoto', city: 'Sokoto' },
    { name: 'Michael Okpara University of Agriculture', type: 'Federal University', state: 'Abia', city: 'Umudike' },
    { name: 'Federal University of Agriculture, Abeokuta', type: 'Federal University', state: 'Ogun', city: 'Abeokuta' },
    { name: 'Federal University Oye-Ekiti', type: 'Federal University', state: 'Ekiti', city: 'Oye-Ekiti' },
    { name: 'Federal University Dutsin-Ma', type: 'Federal University', state: 'Katsina', city: 'Dutsin-Ma' },
    { name: 'Federal University Kashere', type: 'Federal University', state: 'Gombe', city: 'Kashere' },
    { name: 'Federal University Lafia', type: 'Federal University', state: 'Nasarawa', city: 'Lafia' },
    { name: 'Federal University Lokoja', type: 'Federal University', state: 'Kogi', city: 'Lokoja' },
    { name: 'Federal University Ndufu-Alike', type: 'Federal University', state: 'Ebonyi', city: 'Ndufu-Alike' },
    { name: 'Federal University Otuoke', type: 'Federal University', state: 'Bayelsa', city: 'Otuoke' },
    { name: 'Federal University Wukari', type: 'Federal University', state: 'Taraba', city: 'Wukari' },
    { name: 'Federal University Birnin Kebbi', type: 'Federal University', state: 'Kebbi', city: 'Birnin Kebbi' },
    { name: 'Federal University Gusau', type: 'Federal University', state: 'Zamfara', city: 'Gusau' },
    { name: 'Federal University Gashua', type: 'Federal University', state: 'Yobe', city: 'Gashua' },
    { name: 'Nigerian Defence Academy', type: 'Federal University', state: 'Kaduna', city: 'Kaduna' },
    { name: 'Nigerian Police Academy', type: 'Federal University', state: 'Kano', city: 'Wudil' },

    // Federal Universities (Continued)
    { name: 'Federal University of Agriculture, Makurdi', type: 'Federal University', state: 'Benue', city: 'Makurdi' },
    { name: 'Federal University of Petroleum Resources, Effurun', type: 'Federal University', state: 'Delta', city: 'Effurun' },
    { name: 'Federal University of Health Sciences, Otukpo', type: 'Federal University', state: 'Benue', city: 'Otukpo' },
    { name: 'Nigeria Maritime University, Okerenkoko', type: 'Federal University', state: 'Delta', city: 'Okerenkoko' },
    { name: 'Federal University of Health Sciences, Azare', type: 'Federal University', state: 'Bauchi', city: 'Azare' },
    { name: 'Federal University of Health Sciences, Ila-Orangun', type: 'Federal University', state: 'Osun', city: 'Ila-Orangun' },
    { name: 'Federal University of Agriculture, Zuru', type: 'Federal University', state: 'Kebbi', city: 'Zuru' },
    { name: 'Federal University of Technology, Babura', type: 'Federal University', state: 'Jigawa', city: 'Babura' },
    { name: 'Federal University of Technology, Ikot Abasi', type: 'Federal University', state: 'Akwa Ibom', city: 'Ikot Abasi' },
    { name: 'Federal University of Health Sciences, Katsina', type: 'Federal University', state: 'Katsina', city: 'Katsina' },

    // State Universities
    { name: 'Lagos State University', type: 'State University', state: 'Lagos', city: 'Ojo' },
    { name: 'Ladoke Akintola University of Technology', type: 'State University', state: 'Oyo', city: 'Ogbomoso' },
    { name: 'Olabisi Onabanjo University', type: 'State University', state: 'Ogun', city: 'Ago-Iwoye' },
    { name: 'Enugu State University of Science and Technology', type: 'State University', state: 'Enugu', city: 'Enugu' },
    { name: 'Rivers State University', type: 'State University', state: 'Rivers', city: 'Port Harcourt' },
    { name: 'Delta State University', type: 'State University', state: 'Delta', city: 'Abraka' },
    { name: 'Ambrose Alli University', type: 'State University', state: 'Edo', city: 'Ekpoma' },
    { name: 'Adekunle Ajasin University', type: 'State University', state: 'Ondo', city: 'Akungba-Akoko' },
    { name: 'Ekiti State University', type: 'State University', state: 'Ekiti', city: 'Ado-Ekiti' },
    { name: 'Osun State University', type: 'State University', state: 'Osun', city: 'Osogbo' },
    { name: 'Kwara State University', type: 'State University', state: 'Kwara', city: 'Malete' },
    { name: 'Nasarawa State University', type: 'State University', state: 'Nasarawa', city: 'Keffi' },
    { name: 'Benue State University', type: 'State University', state: 'Benue', city: 'Makurdi' },
    { name: 'Kogi State University', type: 'State University', state: 'Kogi', city: 'Anyigba' },
    { name: 'Kaduna State University', type: 'State University', state: 'Kaduna', city: 'Kaduna' },
    { name: 'Niger Delta University', type: 'State University', state: 'Bayelsa', city: 'Wilberforce Island' },
    { name: 'Cross River University of Technology', type: 'State University', state: 'Cross River', city: 'Calabar' },
    { name: 'Abia State University', type: 'State University', state: 'Abia', city: 'Uturu' },
    { name: 'Imo State University', type: 'State University', state: 'Imo', city: 'Owerri' },
    { name: 'Anambra State University of Science and Technology', type: 'State University', state: 'Anambra', city: 'Uli' },
    { name: 'Ebonyi State University', type: 'State University', state: 'Ebonyi', city: 'Abakaliki' },
    { name: 'Kano University of Science and Technology', type: 'State University', state: 'Kano', city: 'Wudil' },
    { name: 'Kebbi State University of Science and Technology', type: 'State University', state: 'Kebbi', city: 'Aliero' },
    { name: 'Sokoto State University', type: 'State University', state: 'Sokoto', city: 'Sokoto' },
    { name: 'Gombe State University', type: 'State University', state: 'Gombe', city: 'Gombe' },
    { name: 'Taraba State University', type: 'State University', state: 'Taraba', city: 'Jalingo' },
    { name: 'Adamawa State University', type: 'State University', state: 'Adamawa', city: 'Mubi' },
    { name: 'Yobe State University', type: 'State University', state: 'Yobe', city: 'Damaturu' },
    { name: 'Bauchi State University', type: 'State University', state: 'Bauchi', city: 'Gadau' },
    { name: 'Zamfara State University', type: 'State University', state: 'Zamfara', city: 'Talata Mafara' },
    { name: 'Plateau State University', type: 'State University', state: 'Plateau', city: 'Bokkos' },
    { name: 'Tai Solarin University of Education', type: 'State University', state: 'Ogun', city: 'Ijebu-Ode' },
    { name: 'Ogun State junction of Health Technology', type: 'State University', state: 'Ogun', city: 'Lishabi' },
    { name: 'Ignatius Ajuru University of Education', type: 'State University', state: 'Rivers', city: 'Rumuolumeni' },
    { name: 'Delta State University of Science and Technology', type: 'State University', state: 'Delta', city: 'Ozoro' },
    { name: 'University of Delta, Agbor', type: 'State University', state: 'Delta', city: 'Agbor' },
    { name: 'Dennis Osadebay University', type: 'State University', state: 'Delta', city: 'Asaba' },
    { name: 'Lagos State University of Science and Technology', type: 'State University', state: 'Lagos', city: 'Ikorodu' },
    { name: 'Lagos State University of Education', type: 'State University', state: 'Lagos', city: 'Ijanikin' },
    { name: 'Borno State University', type: 'State University', state: 'Borno', city: 'Maiduguri' },
    { name: 'Gombe State University of Science and Technology', type: 'State University', state: 'Gombe', city: 'Kumo' },
    { name: 'Bayelsa Medical University', type: 'State University', state: 'Bayelsa', city: 'Yenagoa' },

    // Private Universities
    { name: 'Covenant University', type: 'Private University', state: 'Ogun', city: 'Ota' },
    { name: 'Babcock University', type: 'Private University', state: 'Ogun', city: 'Ilishan-Remo' },
    { name: 'Bowen University', type: 'Private University', state: 'Osun', city: 'Iwo' },
    { name: 'Pan-Atlantic University', type: 'Private University', state: 'Lagos', city: 'Ibeju-Lekki' },
    { name: 'Afe Babalola University', type: 'Private University', state: 'Ekiti', city: 'Ado-Ekiti' },
    { name: 'Bells University of Technology', type: 'Private University', state: 'Ogun', city: 'Ota' },
    { name: 'Caleb University', type: 'Private University', state: 'Lagos', city: 'Imota' },
    { name: 'Crawford University', type: 'Private University', state: 'Ogun', city: 'Igbesa' },
    { name: 'Redeemer\'s University', type: 'Private University', state: 'Osun', city: 'Ede' },
    { name: 'Landmark University', type: 'Private University', state: 'Kwara', city: 'Omu-Aran' },
    { name: 'Lead City University', type: 'Private University', state: 'Oyo', city: 'Ibadan' },
    { name: 'Achievers University', type: 'Private University', state: 'Ondo', city: 'Owo' },
    { name: 'Joseph Ayo Babalola University', type: 'Private University', state: 'Osun', city: 'Ikeji-Arakeji' },
    { name: 'Ajayi Crowther University', type: 'Private University', state: 'Oyo', city: 'Oyo' },
    { name: 'American University of Nigeria', type: 'Private University', state: 'Adamawa', city: 'Yola' },
    { name: 'Bingham University', type: 'Private University', state: 'Nasarawa', city: 'Karu' },
    { name: 'Igbinedion University', type: 'Private University', state: 'Edo', city: 'Okada' },
    { name: 'Madonna University', type: 'Private University', state: 'Anambra', city: 'Okija' },
    { name: 'Elizade University', type: 'Private University', state: 'Ondo', city: 'Ilara-Mokin' },
    { name: 'Oduduwa University', type: 'Private University', state: 'Osun', city: 'Ipetumodu' },
    { name: 'Veritas University', type: 'Private University', state: 'FCT', city: 'Abuja' },
    { name: 'African University of Science and Technology', type: 'Private University', state: 'FCT', city: 'Abuja' },
    { name: 'Nile University of Nigeria', type: 'Private University', state: 'FCT', city: 'Abuja' },
    { name: 'BAZE University', type: 'Private University', state: 'FCT', city: 'Abuja' },
    { name: 'Skyline University Nigeria', type: 'Private University', state: 'Kano', city: 'Kano' },
    { name: 'Greenfield University', type: 'Private University', state: 'Kaduna', city: 'Kaduna' },
    { name: 'Dominion University', type: 'Private University', state: 'Oyo', city: 'Ibadan' },
    { name: 'Chrisland University', type: 'Private University', state: 'Ogun', city: 'Abeokuta' },
    { name: 'Mountain Top University', type: 'Private University', state: 'Ogun', city: 'Makogi Oba' },
    { name: 'Anchor University', type: 'Private University', state: 'Lagos', city: 'Ayobo' },
    { name: 'Augustine University', type: 'Private University', state: 'Lagos', city: 'Epe' },
    { name: 'Hallmark University', type: 'Private University', state: 'Ogun', city: 'Ijebu-Itele' },
    { name: 'McPherson University', type: 'Private University', state: 'Ogun', city: 'Seriki-Sotayo' },
    { name: 'Southwestern University', type: 'Private University', state: 'Ogun', city: 'Okun-Owa' },
    { name: 'Christopher University', type: 'Private University', state: 'Ogun', city: 'Mowe' },
    { name: 'Spiritan University', type: 'Private University', state: 'Abia', city: 'Nneochi' },
    { name: 'Admiralty University of Nigeria', type: 'State University', state: 'Delta', city: 'Ibusa' },
    { name: 'Coal City University', type: 'Private University', state: 'Enugu', city: 'Enugu' },
    { name: 'Godfrey Okoye University', type: 'Private University', state: 'Enugu', city: 'Enugu' },
    { name: 'Caritas University', type: 'Private University', state: 'Enugu', city: 'Amorji-Nike' },
    { name: 'Renaissance University', type: 'Private University', state: 'Enugu', city: 'Ugbawka' },
    { name: 'Salem University', type: 'Private University', state: 'Kogi', city: 'Lokoja' },
    { name: 'Al-Hikmah University', type: 'Private University', state: 'Kwara', city: 'Ilorin' },
    { name: 'Summit University', type: 'Private University', state: 'Kwara', city: 'Offa' },
    { name: 'Crown Hill University', type: 'Private University', state: 'Kwara', city: 'Eiyenkorin' },
    { name: 'Kola Daisi University', type: 'Private University', state: 'Oyo', city: 'Ibadan' },
    { name: 'Precious Cornerstone University', type: 'Private University', state: 'Oyo', city: 'Ibadan' },

    // Polytechnics
    { name: 'Yaba College of Technology', type: 'Polytechnic', state: 'Lagos', city: 'Yaba' },
    { name: 'Lagos State Polytechnic', type: 'Polytechnic', state: 'Lagos', city: 'Ikorodu' },
    { name: 'Federal Polytechnic Ilaro', type: 'Polytechnic', state: 'Ogun', city: 'Ilaro' },
    { name: 'The Polytechnic Ibadan', type: 'Polytechnic', state: 'Oyo', city: 'Ibadan' },
    { name: 'Auchi Polytechnic', type: 'Polytechnic', state: 'Edo', city: 'Auchi' },
    { name: 'Federal Polytechnic Nekede', type: 'Polytechnic', state: 'Imo', city: 'Owerri' },
    { name: 'Kaduna Polytechnic', type: 'Polytechnic', state: 'Kaduna', city: 'Kaduna' },
    { name: 'Federal Polytechnic Bida', type: 'Polytechnic', state: 'Niger', city: 'Bida' },
    { name: 'Institute of Management and Technology', type: 'Polytechnic', state: 'Enugu', city: 'Enugu' },
    { name: 'Kwara State Polytechnic', type: 'Polytechnic', state: 'Kwara', city: 'Ilorin' },
    { name: 'Rufus Giwa Polytechnic', type: 'Polytechnic', state: 'Ondo', city: 'Owo' },
    { name: 'Federal Polytechnic Offa', type: 'Polytechnic', state: 'Kwara', city: 'Offa' },
    { name: 'Federal Polytechnic Ado-Ekiti', type: 'Polytechnic', state: 'Ekiti', city: 'Ado-Ekiti' },
    { name: 'Akwa Ibom State Polytechnic', type: 'Polytechnic', state: 'Akwa Ibom', city: 'Ikot Osurua' },
    { name: 'Federal Polytechnic Bauchi', type: 'Polytechnic', state: 'Bauchi', city: 'Bauchi' },
    { name: 'Federal Polytechnic Oko', type: 'Polytechnic', state: 'Anambra', city: 'Oko' },
    { name: 'Federal Polytechnic Idah', type: 'Polytechnic', state: 'Kogi', city: 'Idah' },
    { name: 'Federal Polytechnic Nasarawa', type: 'Polytechnic', state: 'Nasarawa', city: 'Nasarawa' },
    { name: 'Federal Polytechnic Bali', type: 'Polytechnic', state: 'Taraba', city: 'Bali' },
    { name: 'Federal Polytechnic Ede', type: 'Polytechnic', state: 'Osun', city: 'Ede' },
    { name: 'Federal Polytechnic Mubi', type: 'Polytechnic', state: 'Adamawa', city: 'Mubi' },
    { name: 'Federal Polytechnic Kaura Namoda', type: 'Polytechnic', state: 'Zamfara', city: 'Kaura Namoda' },
    { name: 'Moshood Abiola Polytechnic', type: 'Polytechnic', state: 'Ogun', city: 'Abeokuta' },
    { name: 'Abraham Adesanya Polytechnic', type: 'Polytechnic', state: 'Ogun', city: 'Ijebu-Igbo' },
    { name: 'Gateway ICT Polytechnic', type: 'Polytechnic', state: 'Ogun', city: 'Saapade' },
    { name: 'Osun State Polytechnic, Iree', type: 'Polytechnic', state: 'Osun', city: 'Iree' },
    { name: 'Osun State College of Technology', type: 'Polytechnic', state: 'Osun', city: 'Esa-Oke' },
    { name: 'Delta State Polytechnic, Ogwashi-Uku', type: 'Polytechnic', state: 'Delta', city: 'Ogwashi-Uku' },
    { name: 'Delta State Polytechnic, Otefe-Oghara', type: 'Polytechnic', state: 'Delta', city: 'Oghara' },
    { name: 'Hassan Usman Katsina Polytechnic', type: 'Polytechnic', state: 'Katsina', city: 'Katsina' },
    { name: 'Nuhu Bamalli Polytechnic', type: 'Polytechnic', state: 'Kaduna', city: 'Zaria' },
    { name: 'Ramat Polytechnic', type: 'Polytechnic', state: 'Borno', city: 'Maiduguri' },
    { name: 'Abia State Polytechnic', type: 'Polytechnic', state: 'Abia', city: 'Aba' },

    // Colleges of Education
    { name: 'Federal College of Education, Abeokuta', type: 'College of Education', state: 'Ogun', city: 'Abeokuta' },
    { name: 'Federal College of Education, Akoka', type: 'College of Education', state: 'Lagos', city: 'Akoka' },
    { name: 'Adeniran Ogunsanya College of Education', type: 'College of Education', state: 'Lagos', city: 'Otto/Ijanikin' },
    { name: 'Federal College of Education, Zaria', type: 'College of Education', state: 'Kaduna', city: 'Zaria' },
    { name: 'National Teachers Institute', type: 'College of Education', state: 'Kaduna', city: 'Kaduna' },
    { name: 'Federal College of Education, Kano', type: 'College of Education', state: 'Kano', city: 'Kano' },
    { name: 'Federal College of Education, Okene', type: 'College of Education', state: 'Kogi', city: 'Okene' },
    { name: 'Federal College of Education, Pankshin', type: 'College of Education', state: 'Plateau', city: 'Pankshin' },
    { name: 'Federal College of Education, Katsina', type: 'College of Education', state: 'Katsina', city: 'Katsina' },
    { name: 'Federal College of Education, Obudu', type: 'College of Education', state: 'Cross River', city: 'Obudu' },
    { name: 'Federal College of Education, Gombe', type: 'College of Education', state: 'Gombe', city: 'Gombe' },
    { name: 'Federal College of Education, Kontagora', type: 'College of Education', state: 'Niger', city: 'Kontagora' },
    { name: 'Federal College of Education, Omoku', type: 'College of Education', state: 'Rivers', city: 'Omoku' },
    { name: 'Federal College of Education, Eha-Amufu', type: 'College of Education', state: 'Enugu', city: 'Eha-Amufu' },
    { name: 'Federal College of Education (Special), Oyo', type: 'College of Education', state: 'Oyo', city: 'Oyo' },
    { name: 'Federal College of Education (Technical), Akoka', type: 'College of Education', state: 'Lagos', city: 'Akoka' },
    { name: 'Federal College of Education (Technical), Gombe', type: 'College of Education', state: 'Gombe', city: 'Gombe' },
    { name: 'Federal College of Education (Technical), Potiskum', type: 'College of Education', state: 'Yobe', city: 'Potiskum' },
    { name: 'Federal College of Education (Technical), Bich', type: 'College of Education', state: 'Kano', city: 'Bichi' },
    { name: 'Federal College of Education (Technical), Umunze', type: 'College of Education', state: 'Anambra', city: 'Umunze' },
    { name: 'Federal College of Education (Technical), Asaba', type: 'College of Education', state: 'Delta', city: 'Asaba' },
    { name: 'FCT College of Education, Zuba', type: 'College of Education', state: 'FCT', city: 'Zuba' },
    { name: 'Adeyemi College of Education', type: 'College of Education', state: 'Ondo', city: 'Ondo' },
    { name: 'Emmanuel Alayande College of Education', type: 'College of Education', state: 'Oyo', city: 'Oyo' },
    { name: 'Enugu State College of Education (Technical)', type: 'College of Education', state: 'Enugu', city: 'Enugu' },
    { name: 'Kwara State College of Education, Ilorin', type: 'College of Education', state: 'Kwara', city: 'Ilorin' },
    { name: 'Kwara State College of Education, Oro', type: 'College of Education', state: 'Kwara', city: 'Oro' },
    { name: 'Kwara State College of Education (Technical), Lafiagi', type: 'College of Education', state: 'Kwara', city: 'Lafiagi' },
    { name: 'Niger State College of Education', type: 'College of Education', state: 'Niger', city: 'Minna' },
    { name: 'Nasarawa State College of Education', type: 'College of Education', state: 'Nasarawa', city: 'Akwanga' },
];

async function seedSchools() {
    console.log(`🎓 Seeding ${NIGERIAN_SCHOOLS.length} Nigerian schools...`);

    let created = 0;
    let skipped = 0;

    for (const school of NIGERIAN_SCHOOLS) {
        try {
            await prisma.school.upsert({
                where: { name: school.name },
                update: {
                    type: school.type,
                    state: school.state,
                    city: school.city,
                },
                create: {
                    name: school.name,
                    type: school.type,
                    state: school.state,
                    city: school.city,
                    isApproved: true,
                },
            });
            created++;
        } catch (error) {
            skipped++;
            console.log(`  ⚠ Skipped: ${school.name}`);
        }
    }

    console.log(`\n✅ Done! ${created} schools seeded, ${skipped} skipped.`);
}

seedSchools()
    .catch(console.error)
    .finally(() => prisma.$disconnect());
